//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Admin.java
//  @ Date : 27/12/2013
//  @ Author : 
//
//
//
// commentaire 

package fr.afcepf.atod19.ecommerce.jungle.entity;

import java.io.Serializable;

import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.Table;

@Table
@Inheritance(strategy=InheritanceType.JOINED )
public class Admin extends User implements Serializable{

	private static final long serialVersionUID = 1L;
}
