//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Commande.java
//  @ Date : 27/12/2013
//  @ Author : 
//
//



package fr.afcepf.atod19.ecommerce.jungle.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
@Entity
@Table
public class Commande implements Serializable{
	
	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	private Long numCommande;
	private Float montantTotal;
	private Date dateCommande;
	private Float fraixPort;
	@OneToMany(fetch=FetchType.LAZY, mappedBy="commande")
	private List<LigneCommande> lignesCommande;
	@ManyToOne
	@JoinColumn(name="ref_adresseFacturation")
	private Adresse adresseFacturation;
	@ManyToOne
	@JoinColumn(name="ref_adresseLivraison")
	private Adresse adresseLivraison;
	@ManyToOne
	@JoinColumn(name="ref_client")
	private Client client;
	@Enumerated(EnumType.STRING)
	private EtatCommande etatCommande;
	
	public EtatCommande getEtatCommande() {
		return etatCommande;
	}
	public void setEtatCommande(EtatCommande etatCommande) {
		this.etatCommande = etatCommande;
	}
	public Client getClient() {
		return client;
	}
	public void setClient(Client client) {
		this.client = client;
	}
	public Float getMontantTotal() {
		return montantTotal;
	}
	public void setMontantTotal(Float montantTotal) {
		this.montantTotal = montantTotal;
	}
	public Date getDateCommande() {
		return dateCommande;
	}
	public void setDateCommande(Date dateCommande) {
		this.dateCommande = dateCommande;
	}
	public Float getFraixPort() {
		return fraixPort;
	}
	public void setFraixPort(Float fraixPort) {
		this.fraixPort = fraixPort;
	}
	public List<LigneCommande> getLignesCommande() {
		return lignesCommande;
	}
	public void setLignesCommande(List<LigneCommande> lignesCommande) {
		this.lignesCommande = lignesCommande;
	}
	public Adresse getAdresseFacturation() {
		return adresseFacturation;
	}
	public void setAdresseFacturation(Adresse adresseFacturation) {
		this.adresseFacturation = adresseFacturation;
	}
	public Adresse getAdresseLivraison() {
		return adresseLivraison;
	}
	public void setAdresseLivraison(Adresse adresseLivraison) {
		this.adresseLivraison = adresseLivraison;
	}
	public Long getNumCommande() {
		return numCommande;
	}
	public void setNumCommande(Long numCommande) {
		this.numCommande = numCommande;
	}
	
}
