//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Livre.java
//  @ Date : 27/12/2013
//  @ Author : 
//
//



package fr.afcepf.atod19.ecommerce.jungle.entity;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
@Entity
@Table
public class Livre implements Serializable{
	
	private static final long serialVersionUID = 1L;
	private String titre;
	@Id
	private String numeroISBN;
	private Float prix;
	private Integer nombreDePages;
	private Integer qteEnStock;
	private Date datePublication;
	@OneToMany(fetch=FetchType.LAZY, mappedBy="livre")
	private List<ImageLivre> imagesLivre;
	@ManyToMany( fetch = FetchType.LAZY)
	@JoinTable(
			   name = "auteurLivre",
			   joinColumns ={@JoinColumn(name = "numISBN")},
		       inverseJoinColumns = {@JoinColumn(name = "numAut")}
	         )
	private List<Auteur> auteurs;
	@ManyToOne
	@JoinColumn(name="ref_editeur")
	private Editeur editeur;
	@ManyToOne
	@JoinColumn(name="ref_categorie")
	private Categorie categorie;
	
	public Livre() {
		auteurs = new ArrayList<Auteur>();
	}
	public String getTitre() {
		return titre;
	}
	public void setTitre(String titre) {
		this.titre = titre;
	}
	public String getNumeroISBN() {
		return numeroISBN;
	}
	public void setNumeroISBN(String numeroISBN) {
		this.numeroISBN = numeroISBN;
	}
	public Float getPrix() {
		return prix;
	}
	public void setPrix(Float prix) {
		this.prix = prix;
	}
	public Integer getNombreDePages() {
		return nombreDePages;
	}
	public void setNombreDePages(Integer nombreDePages) {
		this.nombreDePages = nombreDePages;
	}
	public Integer getQteEnStock() {
		return qteEnStock;
	}
	public void setQteEnStock(Integer qteEnStock) {
		this.qteEnStock = qteEnStock;
	}
	public Date getDatePublication() {
		return datePublication;
	}
	public void setDatePublication(Date datePublication) {
		this.datePublication = datePublication;
	}
	public List<ImageLivre> getImagesLivre() {
		return imagesLivre;
	}
	public void setImagesLivre(List<ImageLivre> imagesLivre) {
		this.imagesLivre = imagesLivre;
	}
	public List<Auteur> getAuteurs() {
		return auteurs;
	}
	public void setAuteurs(List<Auteur> auteurs) {
		this.auteurs = auteurs;
	}
	public Editeur getEditeur() {
		return editeur;
	}
	public void setEditeur(Editeur editeur) {
		this.editeur = editeur;
	}
	public Categorie getCategorie() {
		return categorie;
	}
	public void setCategorie(Categorie categorie) {
		this.categorie = categorie;
	}
	
}
